---
# File: roles/shell/tasks/dotfiles.yml

- name: Clone dotfiles
  git: "repo={{ dotfiles_repo }} dest={{ dotfiles_path }} recursive=true accept_hostkey=yes"
  register: dotfiles

- name: Install dotfiles
  shell: "{{ dotfiles_init_cmd }}"
  when: dotfiles | changed and dotfiles_init_cmd is defined

- name: Clone emacs.d
  git: >
    repo="{{ emacsd_repo }}"
    dest="{{ emacsd_path }}"
