---
# File: roles/shell/tasks/main.yml

- name: Check current shell
  shell: echo $SHELL
  register: current_shell

- name: Set default shell
  shell: chsh -s {{ shell }}
  when: current_shell.stdout != "{{ shell }}"
