---

- name: Install homebrew packages
  homebrew: name={{ item }} state=present
  with_items: "{{ brews }}"

- name: Install apps with brew-cask
  homebrew_cask: name={{ item }} state=present
  with_items: "{{ casks }}"

