---
- hosts: laptops
  roles: []

- hosts: laptops
  gather_facts: no
  environment:
    PATH: "{{ ansible_env.PATH }}:/opt/homebrew/bin:{{ ansible_env.HOME }}/.rbenv/bin:{{ ansible_env.HOME }}/.rbenv/plugins/ruby-build/bin"
  roles:
    - jgkim.brew
    - shell
    - dev
    - software
    - fonts
    - jekyll
    - vm_host
    - keepassx
    - security

