---
- hosts: all
  environment:
    PATH: "{{ ansible_env.PATH }}:/opt/homebrew/bin:{{ ansible_env.HOME }}/.rbenv/bin:{{ ansible_env.HOME }}/.rbenv/plugins/ruby-build/bin"
  roles:
    - jgkim.brew
    - common
    - shell
    - dev-common
    - dev
    - software
    - fonts
    - jekyll
    - vm-host

