---
# File: tasks/homebrew.yml

- name: Check if homebrew is installed
  stat: path=/usr/local/bin/brew
  register: brew_stat

- name: Install homebrew
  shell: ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
  when: brew_stat.stat.exists == false

- name: Install brew-cask
  homebrew: name=caskroom/cask/brew-cask state=present

- name: Install homebrew packages
  homebrew: name={{ item }} state=present
  with_items: brews

- name: Check for installed casks
  shell: brew cask list --appdir={{ applications_path | quote }}
  register: installed_applications
  ignore_errors: true

- name: Install apps with brew-cask
  shell: brew cask install --appdir={{ applications_path | quote }} {{ item }}
  with_items: applications
  when: "item not in installed_applications.stdout.splitlines()"
