---
# File: tasks/shell.yml

- name: Check current shell
  shell: echo $SHELL
  register: current_shell

- name: Set zsh as default shell
  shell: chsh -s /bin/zsh
  when: current_shell.stdout != '/bin/zsh'
