- name: Require password to unlock screen
  osx_defaults:
    domain: com.apple.screensaver
    key: askForPassword
    type: boolean
    value: yes

- name: Require password immediately after locking
  osx_defaults:
    domain: com.apple.screensaver
    key: askForPasswordDelay
    type: float
    value: 0

- name: Show all extensions
  osx_defaults:
    key: AppleShowAllExtensions
    type: boolean
    value: yes

- name: Reload applications to make settings live
  command: killall Dock Finder
