---
# File: roles/dotfiles/tasks/main.yml

- name: Clone dotfiles
  git: "repo={{ dotfiles_repo }} dest={{ dotfiles_path }} recursive=true"
  register: dotfiles

- name: Check if dotfiles contains install.sh
  stat: path="{{ dotfiles_path }}/install.sh"
  register: dotfiles_stat

- name: Install dotfiles
  shell: "{{ dotfiles_path }}/install.sh --force"
  when: dotfiles.changed == true and dotfiles_stat.stat.exists == true
