---

- include: structure.yml
  tags:
    - dev
    - dev_structure

- include: cpp.yml
  tags:
    - dev
    - dev_cpp

- include: db.yml
  tags:
    - dev
    - dev_db

- include: lisp.yml
  tags:
    - dev
    - dev_lisp

- include: python.yml
  tags:
    - dev
    - dev_python
