---
# File: roles/dev-php/tasks/main.yml

- name: Tap PHP repo
  homebrew_tap: tap=homebrew/php
  when: ansible_os_family == "Darwin"

- name: Install PHP | OS X
  homebrew: pkg={{ item }} state=present
  with_items:
    - php56
  when: ansible_os_family == "Darwin"

- name: Configure webtatic repository
  become: yes
  yum: name={{ item }} state=present
  with_items:
    - https://mirror.webtatic.com/yum/el7/epel-release.rpm
    - https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
  when: ansible_distribution == "CentOS"

- name: Install PHP | CentOS
  become: yes
  yum: pkg={{ item }} state=present
  with_items:
    - php56w-cli
    - php56w-fpm
    - php56w-pdo
    - php56w-pecl-memcached
    - php56w-xml
  when: ansible_distribution == "CentOS"
