---

- name: Install python software
  homebrew: pkg={{ item }} state=installed
  with_items:
    - pyenv
    - pyenv-virtualenv
    - python
    - python3
  when: ansible_os_family == "Darwin"

- name: Install pips
  pip:
    name:
      - rope
      - jedi
      - flake8
      - importmagic
      - autopep8
      - yapf
      - pygments
      - virtualenv
    extra_args: "--user"

# @TODO: CentOS
