---

- name: Install python software
  homebrew: pkg={{ item }} state=installed
  with_items:
    - pyenv
    - pyenv-virtualenv
    - python
    - python3
  when: ansible_os_family == "Darwin"

# @TODO: CentOS
