---

- name: Install rbenv stuff | OS X
  homebrew: name={{ item }}
  with_items:
    - rbenv
    - ruby-build
  when: ansible_os_family == "Darwin"

- name: Install rbenv | CentOS
  git: >
    repo=git://github.com/sstephenson/rbenv.git
    dest=~/.rbenv
  when: ansible_distribution == "CentOS"

- name: Install ruby-build | CentOS
  git: >
    repo=git://github.com/sstephenson/ruby-build.git
    dest=~/.rbenv/plugins/ruby-build
  when: ansible_distribution == "CentOS"

- name: Install ruby versions
  shell: rbenv install {{ item }}
  args:
    creates: ~/.rbenv/versions/{{ item }}
  with_items: ruby_versions

- name: Install ruby gems
  gem: name="{{ item[0] }}" executable=~/.rbenv/shims/gem user_install=no
  notify: rehash rbenv
  environment:
    RBENV_VERSION: "{{ item[1] }}"
  with_nested:
    - ruby_gems
    - ruby_versions
  when: ansible_os_family == "Darwin"

- name: Set default ruby version
  shell: rbenv global {{ ruby_default }}
  args:
    creates: ~/.rbenv/version
  when: ansible_os_family == "Darwin"

# @TODO: CentOS

